PenguinLearning:
  measure: reward
  thresholds: [-0.1, 0.7, 1.7, 1.7, 1.7, 2.7, 2.7]
  min_lesson_length: 80
  signal_smoothing: true
  parameters:
    fish_speed: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5, 0.5]
    feed_radius: [6.0, 5.0, 4.0, 3.0, 2.0, 1.0, 0.5, 0.2]
